<%
require "uri"

def render_scheme_yaml(database_url)
  uri = URI.parse(database_url || "")
  {
    :adapter  => uri.scheme == "postgres" ? "postgresql" : uri.scheme,
    :database => uri.path[1..-1],
    :username => uri.user,
    :password => uri.password,
    :host     => uri.host,
    :port     => uri.port
  }.map { |k,v|
    "  #{k}: #{v}"
  }.join("\n")
rescue URI::InvalidURIError
  raise "invalid DATABASE_URL"
end
%>

<% %w[development test].map do |env| %>
<%= "#{env}:" %>
<%= render_scheme_yaml(ENV["DATABASE_URL_#{env.upcase}"]) %>
  pool: 5
  timeout: 5000
<% end %>

production:
<%= render_scheme_yaml(ENV["DATABASE_URL"]) %>
  pool: 5
  timeout: 5000
